# Site settings
title: Arabidopsis Small RNA Project
description: > # this means to ignore newlines until "baseurl:"
  The purpose of the Arabidopsis Small RNA Project (ASRP) website is to provide access to data and resources
  from the Carrington laboratory.
baseurl: "/asrp" # the subpath of your site, e.g. /blog/
url: "http://carringtonlab.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
